name: Publish Docker
on: [push]
jobs:
  minify:
    name: Minify images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Download and use webp converter
        run: |
          wget https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-1.1.0-rc2-linux-x86-64.tar.gz
          mkdir webp
          tar -xvzf libwebp-1.1.0-rc2-linux-x86-64.tar.gz -C webp
          for file in website/images/projects/*; do webp/libwebp-1.1.0-rc2-linux-x86-64/bin/cwebp -q 80 "$file" -o "${file%.*}.webp"; done
      - name: Setup node js
        uses: actions/setup-node@v1
        with:
          node-version: 13
      - name: Install uglifyjs
        run: npm install uglify-es -g
      - name: Minify js-scripts
        run: |
          uglifyjs website/js/dotsBackground.js --compress --mangle --output website/js/dotsBackground.js
      - name: Install cssnano and PostCSS
        run: |
          npm install cssnano --save-dev
          npm install postcss-cli --global
      - name: Minify css
        run: |
          postcss website/style/general.css -r true
          postcss website/style/navBar.css -r true
          postcss website/style/blog.css -r true
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: website
          path: website/

  build:
    runs-on: ubuntu-latest
    needs: minify
    if: contains(github.ref, 'master')
    steps:
      - uses: actions/checkout@master
      - name: Download artifacts
        uses: actions/download-artifact@v1
        with:
          name: website
      - name: Build and Publish Image
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: lol3r/personal_site
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with:
          host: lol3r.net
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: docker pull lol3r/personal_site && cd personal_compose/ && docker-compose up -d
