name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build and Publish Image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: lol3r/personal_site
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Deploy to production
      if: contains(github.ref, 'master')
      run: |
        'which ssh-agent || ( apt-get install -qq openssh-client )'
        eval $(ssh-agent -s)
        ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 -d)
        mkdir -p ~/.ssh
        '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
        ssh root@lol3r.net "docker pull lol3r/personal_site:latest && cd personal_compose/ && docker-compose up -d && exit"
